sudo: false
language: java

jdk:
- oraclejdk8

services:
- docker

install:
- gradle build

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t "$DOCKER_LOGIN_HOST"/memberservice:latest .;
    echo "$DOCKER_LOGIN_KEY" | docker login -u "$DOCKER_LOGIN_USER" --password-stdin "$DOCKER_LOGIN_HOST";
    docker push "$DOCKER_LOGIN_HOST"/memberservice;
    fi